### ISSUE TITLE
Courses Page - Dummy Data

### ISSUE THREAD

**Issue by GauravTalreja** [GauravTalreja/ebb#15] opened 2023-06-16 03:46 UTC
- Hardcode some data with temporary models
- Design the UI and make it pretty
- Make the UI reactive (it should be able to affect the state of the page, even if it's not being sent to the backend)

**Comment by SaumyaKhati** [comment] 2023-06-23 02:05
@GauravTalreja, is this a duplicate of #21?

**Closed as completed** 2023-06-23 02:06 UTC
